In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import svm
#import antropy as ant
import os
from urllib.parse import urlparse

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
xtr = '/content/drive/MyDrive/iCV/fs/X_train_raw.csv'
X_train = pd.read_csv(xtr)
X_train = X_train.iloc[: , 1:]
X_train

0         1         2         3         4         5         6  \
0    0.988958  0.067259  0.438319  1.137520  1.089087  1.029346  2.717865   
1    0.992118  0.298309  0.453541  1.035824  0.962622  1.029659  3.088979   
2    0.992801  0.058871  0.287075  0.397559  0.357879  1.030003  2.113270   
3    0.987188  0.057681  0.602902  1.423848  1.415723  1.028655  3.146533   
4    0.986123  0.025413  0.196409  0.136494  0.122143  1.028592  1.810684   
..        ...       ...       ...       ...       ...       ...       ...   
355  0.983089  0.161635  0.393969  1.094124  1.030290  1.028435  3.065097   
356  0.982308  0.103594  0.265516  0.966786  0.900580  1.027994  2.494608   
357  0.985058  0.126618  0.568801  1.265913  1.228012  1.028246  2.885123   
358  0.992508  0.445656  0.819027  0.883126  0.783380  1.029940  2.428537   
359  0.990079  0.156516  0.408121  1.116311  1.026929  1.029534  2.379199   

            7         8         9  ...       254       255       256  \
0    1.788580  1.093887  0.342011  ...  0.066450  0.255464  0.378418   
1    1.696088  1.277951  0.297930  ...  0.056870  0.559084  1.214606   
2    1.780102  1.201428  0.131788  ...  0.059250  0.227857  0.266797   
3    1.733653  1.153769  0.474764  ...  0.071884  0.351816  0.619748   
4    1.709202  1.288431  0.065314  ...  0.102542  0.237914  0.042205   
..        ...       ...       ...  ...       ...       ...       ...   
355  1.708673  1.172339  0.325704  ...  0.120266  0.500772  1.392109   
356  1.656249  1.077622  0.276555  ...  0.098765  0.185685  0.667569   
357  1.623425  1.086856  0.406856  ...  0.090668  0.397901  1.011695   
358  1.908535  0.603238  1.286764  ...  0.399448  0.258115  0.323642   
359  1.729326  1.136918  0.343146  ...  0.249625  0.121560  0.682098   

          257       258       259       260       261       262        263  
0    0.301583  1.026886  1.934144  1.787019  1.179408  0.122471  12.327245  
1    1.169410  1.027235  2.663392  1.491562  1.138520  0.366620   3.992147  
2    0.231607  1.028466  1.970670  1.708642  1.142292  0.095519  15.733984  
3    0.531960  1.028057  1.971293  1.740401  1.172728  0.181499   8.444490  
4    0.036819  1.025613  1.348709  1.360055  1.835939  0.022456  58.220748  
..        ...       ...       ...       ...       ...       ...        ...  
355  1.387328  1.030034  2.942004  1.821198  1.040095  0.515954   3.198588  
356  0.584481  1.029315  2.233755  1.685911  1.205024  0.192472   8.261542  
357  0.881275  1.028812  2.920365  1.608635  1.052227  0.301593   5.155438  
358  0.217407  1.033164  2.056919  1.891893  1.443804  0.190767   9.321579  
359  0.521668  1.030221  2.528674  1.936218  1.002913  0.243380   6.976634  

[360 rows x 264 columns]

In [ ]:
ytr = '/content/drive/MyDrive/iCV/fs/y_train_raw.csv'
y_train = pd.read_csv(ytr)
y_train = y_train.iloc[: , 1:]
y_train

label
0        2
1        3
2        0
3        4
4        2
..     ...
355      3
356      3
357      4
358      1
359      1

[360 rows x 1 columns]

In [ ]:
xva = '/content/drive/MyDrive/iCV/fs/X_val_raw.csv'
X_val = pd.read_csv(xva)
X_val = X_val.iloc[: , 1:]
X_val

0         1         2         3         4         5         6  \
0    0.995164  0.051621  0.269808  0.206101  0.196134  1.031218  1.861980   
1    0.985997  0.102932  0.218478  0.064754  0.061613  1.029596  1.500932   
2    0.991985  0.017636  0.399456  1.170486  1.133108  1.029722  2.589420   
3    0.990450  0.018601  0.320123  0.957016  0.904883  1.029909  2.548556   
4    0.994833  0.016566  0.462472  1.143927  1.090907  1.030377  2.525033   
..        ...       ...       ...       ...       ...       ...       ...   
175  0.882409  0.023091  0.155039  0.010222  0.009194  1.021647  1.123145   
176  0.960432  0.013519  0.275084  0.180373  0.162540  1.024814  1.780431   
177  0.977803  0.011702  0.162595  0.047656  0.039647  1.027235  1.525093   
178  0.970531  0.062681  0.194648  0.025660  0.024187  1.027077  1.317382   
179  0.969495  0.025261  0.365572  0.134647  0.119047  1.025964  1.671416   

            7         8         9  ...       254       255       256  \
0    1.756039  1.450327  0.088556  ...  0.105581  0.306146  0.849327   
1    1.553031  1.687539  0.038263  ...  0.095922  0.301407  0.624897   
2    1.814638  1.183937  0.348323  ...  0.199932  0.734944  1.617649   
3    1.799551  1.249977  0.269780  ...  0.487614  0.382417  1.299062   
4    1.770888  1.262652  0.328719  ...  0.097255  0.399070  1.083188   
..        ...       ...       ...  ...       ...       ...       ...   
175  1.258411  1.889803  0.004861  ...  0.052939  0.179788  0.074452   
176  1.722486  1.323134  0.069667  ...  0.035263  0.136553  0.786438   
177  1.769132  1.444900  0.029762  ...  0.259940  0.223814  0.365137   
178  1.607664  1.694644  0.014673  ...  0.256985  0.377422  0.305499   
179  1.596362  1.571694  0.063082  ...  0.050910  0.266407  0.071539   

          257       258       259       260       261       262        263  
0    0.756833  1.031807  2.469174  1.913739  1.151683  0.267132   6.285164  
1    0.531487  1.032332  2.620042  1.862623  1.391247  0.206928   8.199596  
2    1.738474  1.030751  3.872249  1.863218  0.952004  0.773545   2.068008  
3    1.253296  1.030782  3.347090  1.920830  0.963859  0.452147   3.687073  
4    1.036873  1.028969  2.486329  1.858499  1.083576  0.308553   5.098603  
..        ...       ...       ...       ...       ...       ...        ...  
175  0.072896  1.027298  1.617265  1.805961  1.373865  0.038867  38.850806  
176  0.678459  1.027013  2.299244  1.900372  0.966266  0.242985   6.201316  
177  0.318589  1.028340  1.990945  1.884109  1.172551  0.118945  12.647910  
178  0.266874  1.026886  1.759670  1.745421  1.634131  0.118662  11.628444  
179  0.060205  1.027045  1.500570  1.688890  1.486604  0.045165  33.843184  

[180 rows x 264 columns]

In [ ]:

yva = '/content/drive/MyDrive/iCV/fs/y_val_raw.csv'
y_val = pd.read_csv(yva)
y_val = y_val.iloc[: , 1:]
y_val

label
0        1
1        4
2        3
3        0
4        0
..     ...
175      1
176      5
177      3
178      1
179      5

[180 rows x 1 columns]

In [ ]:
xte = '/content/drive/MyDrive/iCV/fs/X_test_raw.csv'
X_test = pd.read_csv(xte)
X_test = X_test.iloc[: , 1:]
X_test

0         1         2         3         4         5         6  \
0    0.996237  0.048759  0.588373  1.390629  1.389042  1.031218  2.797260   
1    0.995383  0.044148  0.648816  1.531867  1.600085  1.030938  3.684032   
2    0.994891  0.224743  0.362383  1.178438  1.021117  1.032394  2.549771   
3    0.997518  0.040468  0.272218  1.168475  1.045730  1.031714  3.159960   
4    0.994241  0.066455  0.542172  1.376329  1.330798  1.031435  3.134958   
..        ...       ...       ...       ...       ...       ...       ...   
175  0.992095  0.076647  0.474044  1.113328  1.058204  1.029878  2.432569   
176  0.990722  0.021446  0.301952  0.552228  0.495272  1.029377  2.192434   
177  0.986720  0.024979  0.295273  0.707784  0.646462  1.028561  2.255046   
178  0.989385  0.075441  0.231241  0.403504  0.361225  1.029440  2.123087   
179  0.987396  0.068627  0.499572  1.107048  1.035529  1.028718  2.545530   

            7         8         9  ...       254       255       256  \
0    1.764320  1.155365  0.528718  ...  0.170867  0.119997  0.269264   
1    1.858902  1.019620  0.700534  ...  0.101933  0.265427  0.162317   
2    1.950440  0.784293  0.588348  ...  0.327029  0.259801  0.597911   
3    1.865577  1.005572  0.407527  ...  0.138998  0.151563  0.114885   
4    1.924620  0.848977  0.671696  ...  0.245925  0.248837  0.178221   
..        ...       ...       ...  ...       ...       ...       ...   
175  1.704809  1.269992  0.329389  ...  0.075268  0.380783  0.634272   
176  1.688792  1.340293  0.167406  ...  0.049797  0.279607  0.904297   
177  1.749076  1.159118  0.190368  ...  0.042219  0.436520  1.102213   
178  1.699890  1.262571  0.127183  ...  0.068431  0.252484  0.570826   
179  1.756680  1.149844  0.333578  ...  0.087838  0.427098  1.148300   

          257       258       259       260       261       262        263  
0    0.227565  1.031621  2.191226  1.950690  1.272079  0.120209  14.019022  
1    0.162980  1.030502  1.748049  1.941028  1.145546  0.076101  21.686228  
2    0.456816  1.031155  2.484020  1.918490  1.265494  0.205685   8.096128  
3    0.105266  1.028907  1.691321  1.779848  1.453161  0.062901  25.120872  
4    0.156164  1.028938  1.804777  1.875286  1.124607  0.080634  19.923217  
..        ...       ...       ...       ...       ...       ...        ...  
175  0.558961  1.027773  2.313929  1.648317  1.483902  0.183832   8.397645  
176  0.809234  1.029503  2.691081  1.774181  1.126665  0.284591   5.731876  
177  1.041617  1.027425  2.696721  1.696681  1.111990  0.313017   4.944807  
178  0.506152  1.026886  2.274052  1.682471  1.326216  0.156895   9.545513  
179  1.088418  1.030533  2.576468  1.798309  1.140475  0.351366   4.702300  

[180 rows x 264 columns]

In [ ]:
yte = '/content/drive/MyDrive/iCV/fs/y_test_raw.csv'
y_test = pd.read_csv(yte)
y_test = y_test.iloc[: , 1:]
y_test

label
0        2
1        5
2        0
3        5
4        4
..     ...
175      5
176      5
177      0
178      3
179      2

[180 rows x 1 columns]

In [ ]:
y_train['label'].value_counts()

2    60
3    60
0    60
4    60
1    60
5    60
Name: label, dtype: int64

In [ ]:
y_val['label'].value_counts()

1    30
4    30
3    30
0    30
5    30
2    30
Name: label, dtype: int64

In [ ]:
y_test['label'].value_counts()

2    30
5    30
0    30
4    30
3    30
1    30
Name: label, dtype: int64

In [ ]:

X_trainest = X_train.append(X_test, ignore_index=True)
y_trainest = y_train.append(y_test, ignore_index=True)


<ipython-input-12-84e0294d19e0>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  X_trainest = X_train.append(X_test, ignore_index=True)
<ipython-input-12-84e0294d19e0>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y_trainest = y_train.append(y_test, ignore_index=True)


In [ ]:
X_trainest

0         1         2         3         4         5         6  \
0    0.988958  0.067259  0.438319  1.137520  1.089087  1.029346  2.717865   
1    0.992118  0.298309  0.453541  1.035824  0.962622  1.029659  3.088979   
2    0.992801  0.058871  0.287075  0.397559  0.357879  1.030003  2.113270   
3    0.987188  0.057681  0.602902  1.423848  1.415723  1.028655  3.146533   
4    0.986123  0.025413  0.196409  0.136494  0.122143  1.028592  1.810684   
..        ...       ...       ...       ...       ...       ...       ...   
535  0.992095  0.076647  0.474044  1.113328  1.058204  1.029878  2.432569   
536  0.990722  0.021446  0.301952  0.552228  0.495272  1.029377  2.192434   
537  0.986720  0.024979  0.295273  0.707784  0.646462  1.028561  2.255046   
538  0.989385  0.075441  0.231241  0.403504  0.361225  1.029440  2.123087   
539  0.987396  0.068627  0.499572  1.107048  1.035529  1.028718  2.545530   

            7         8         9  ...       254       255       256  \
0    1.788580  1.093887  0.342011  ...  0.066450  0.255464  0.378418   
1    1.696088  1.277951  0.297930  ...  0.056870  0.559084  1.214606   
2    1.780102  1.201428  0.131788  ...  0.059250  0.227857  0.266797   
3    1.733653  1.153769  0.474764  ...  0.071884  0.351816  0.619748   
4    1.709202  1.288431  0.065314  ...  0.102542  0.237914  0.042205   
..        ...       ...       ...  ...       ...       ...       ...   
535  1.704809  1.269992  0.329389  ...  0.075268  0.380783  0.634272   
536  1.688792  1.340293  0.167406  ...  0.049797  0.279607  0.904297   
537  1.749076  1.159118  0.190368  ...  0.042219  0.436520  1.102213   
538  1.699890  1.262571  0.127183  ...  0.068431  0.252484  0.570826   
539  1.756680  1.149844  0.333578  ...  0.087838  0.427098  1.148300   

          257       258       259       260       261       262        263  
0    0.301583  1.026886  1.934144  1.787019  1.179408  0.122471  12.327245  
1    1.169410  1.027235  2.663392  1.491562  1.138520  0.366620   3.992147  
2    0.231607  1.028466  1.970670  1.708642  1.142292  0.095519  15.733984  
3    0.531960  1.028057  1.971293  1.740401  1.172728  0.181499   8.444490  
4    0.036819  1.025613  1.348709  1.360055  1.835939  0.022456  58.220748  
..        ...       ...       ...       ...       ...       ...        ...  
535  0.558961  1.027773  2.313929  1.648317  1.483902  0.183832   8.397645  
536  0.809234  1.029503  2.691081  1.774181  1.126665  0.284591   5.731876  
537  1.041617  1.027425  2.696721  1.696681  1.111990  0.313017   4.944807  
538  0.506152  1.026886  2.274052  1.682471  1.326216  0.156895   9.545513  
539  1.088418  1.030533  2.576468  1.798309  1.140475  0.351366   4.702300  

[540 rows x 264 columns]

In [ ]:
y_trainest

label
0        2
1        3
2        0
3        4
4        2
..     ...
535      5
536      5
537      0
538      3
539      2

[540 rows x 1 columns]

In [ ]:
y_trainest['label'].value_counts()

2    90
3    90
0    90
4    90
1    90
5    90
Name: label, dtype: int64

## ML Detection

In [ ]:
import pandas as pd
import imblearn
import lightgbm as lgb
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import linear_model
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from matplotlib import pyplot

In [ ]:
svclassifier1 = SVC(kernel='rbf').fit(X_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_rbf2 = svclassifier1.predict(X_val)

print(confusion_matrix(y_val,y_pred_m1_svm_rbf2))
print(classification_report(y_val,y_pred_m1_svm_rbf2))

[[ 2  0  0  1 25  2]
 [ 2  2  0  1 22  3]
 [ 0  1  0  1 28  0]
 [ 1  1  1  2 25  0]
 [ 1  4  1  2 21  1]
 [ 1  5  0  0 19  5]]
              precision    recall  f1-score   support

           0       0.29      0.07      0.11        30
           1       0.15      0.07      0.09        30
           2       0.00      0.00      0.00        30
           3       0.29      0.07      0.11        30
           4       0.15      0.70      0.25        30
           5       0.45      0.17      0.24        30

    accuracy                           0.18       180
   macro avg       0.22      0.18      0.13       180
weighted avg       0.22      0.18      0.13       180



In [ ]:
svclassifier2 = SVC(kernel='poly').fit(X_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_polynomial2 = svclassifier2.predict(X_val)

print(confusion_matrix(y_val,y_pred_m1_svm_polynomial2))
print(classification_report(y_val,y_pred_m1_svm_polynomial2))

[[ 1  0  0  1 28  0]
 [ 0  1  1  1 27  0]
 [ 0  0  1  0 29  0]
 [ 0  2  1  1 26  0]
 [ 0  2  1  2 25  0]
 [ 0  1  0  0 28  1]]
              precision    recall  f1-score   support

           0       1.00      0.03      0.06        30
           1       0.17      0.03      0.06        30
           2       0.25      0.03      0.06        30
           3       0.20      0.03      0.06        30
           4       0.15      0.83      0.26        30
           5       1.00      0.03      0.06        30

    accuracy                           0.17       180
   macro avg       0.46      0.17      0.09       180
weighted avg       0.46      0.17      0.09       180



In [ ]:
svclassifier3 = SVC(kernel='sigmoid').fit(X_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_sigm2 = svclassifier3.predict(X_val)

print(confusion_matrix(y_val,y_pred_m1_svm_sigm2))
print(classification_report(y_val,y_pred_m1_svm_sigm2))

[[ 4  0 11  0  3 12]
 [ 4  0  8  0  3 15]
 [ 5  0 11  0  2 12]
 [ 5  2 14  0  4  5]
 [ 6  1  8  0  3 12]
 [ 0  0 14  0  4 12]]
              precision    recall  f1-score   support

           0       0.17      0.13      0.15        30
           1       0.00      0.00      0.00        30
           2       0.17      0.37      0.23        30
           3       0.00      0.00      0.00        30
           4       0.16      0.10      0.12        30
           5       0.18      0.40      0.24        30

    accuracy                           0.17       180
   macro avg       0.11      0.17      0.12       180
weighted avg       0.11      0.17      0.12       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
rf = RandomForestClassifier().fit(X_trainest, y_trainest)

<ipython-input-23-b5938cee6349>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf = RandomForestClassifier().fit(X_trainest, y_trainest)


In [ ]:
y_pred_m1_rf2 = rf.predict(X_val)
print(confusion_matrix(y_val,y_pred_m1_rf2))
print(classification_report(y_val,y_pred_m1_rf2))

[[ 6  2 10  8  2  2]
 [ 5  4  7  6  3  5]
 [ 6  4 14  5  0  1]
 [ 7  2 10  6  3  2]
 [ 4  5  6  9  2  4]
 [ 2  4  8  9  3  4]]
              precision    recall  f1-score   support

           0       0.20      0.20      0.20        30
           1       0.19      0.13      0.16        30
           2       0.25      0.47      0.33        30
           3       0.14      0.20      0.16        30
           4       0.15      0.07      0.09        30
           5       0.22      0.13      0.17        30

    accuracy                           0.20       180
   macro avg       0.19      0.20      0.19       180
weighted avg       0.19      0.20      0.19       180



In [ ]:
gnb = BernoulliNB().fit(X_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_naive_bernoulli2 = gnb.predict(X_val)
print(confusion_matrix(y_val,y_pred_m1_naive_bernoulli2))
print(classification_report(y_val,y_pred_m1_naive_bernoulli2))

[[27  0  0  3  0  0]
 [28  1  0  1  0  0]
 [29  0  0  1  0  0]
 [28  0  0  2  0  0]
 [29  0  0  1  0  0]
 [29  0  0  1  0  0]]
              precision    recall  f1-score   support

           0       0.16      0.90      0.27        30
           1       1.00      0.03      0.06        30
           2       0.00      0.00      0.00        30
           3       0.22      0.07      0.10        30
           4       0.00      0.00      0.00        30
           5       0.00      0.00      0.00        30

    accuracy                           0.17       180
   macro avg       0.23      0.17      0.07       180
weighted avg       0.23      0.17      0.07       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
model = lgb.LGBMClassifier().fit(X_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003210 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 47177
[LightGBM] [Info] Number of data points in the train set: 540, number of used features: 264
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [

In [ ]:
y_pred_m1_lgb2 = model.predict(X_val)
print(confusion_matrix(y_val,y_pred_m1_lgb2))
print(classification_report(y_val,y_pred_m1_lgb2))

[[ 5  5  9  2  7  2]
 [ 6  5  8  5  2  4]
 [ 6  1 13  6  2  2]
 [ 3  3 11  6  4  3]
 [ 8  1  8  7  2  4]
 [ 3  4  9  3  5  6]]
              precision    recall  f1-score   support

           0       0.16      0.17      0.16        30
           1       0.26      0.17      0.20        30
           2       0.22      0.43      0.30        30
           3       0.21      0.20      0.20        30
           4       0.09      0.07      0.08        30
           5       0.29      0.20      0.24        30

    accuracy                           0.21       180
   macro avg       0.21      0.21      0.20       180
weighted avg       0.21      0.21      0.20       180



# ML Detection with Feature Selection
## Variance Threshold

In [ ]:
from sklearn.feature_selection import VarianceThreshold

In [ ]:
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel1 = sel.fit(X_trainest)
sel1 = sel.transform(X_trainest)
Xvarthres_trainest =  pd.DataFrame(sel1)
Xvarthres_trainest.head()

0         1         2          3         4         5         6   \
0  1.137520  1.089087  2.717865   4.596034  1.180104  1.072182  6.126741   
1  1.035824  0.962622  3.088979   5.301953  1.195381  1.096464  6.202377   
2  0.397559  0.357879  2.113270  12.104865  1.250260  1.146009  6.426118   
3  1.423848  1.415723  3.146533   3.300545  1.232010  1.139352  4.310898   
4  0.136494  0.122143  1.810684  23.507708  1.295083  1.204223  4.971171   

         7         8         9   ...        84        85        86        87  \
0  0.517826  1.227148  1.021561  ...  1.735719  1.595204  1.719024  3.530533   
1  0.553621  1.228078  1.092782  ...  4.164196  1.092795  1.019893  2.395939   
2  0.650672  1.282335  0.786908  ...  3.465410  1.052954  1.001427  2.702160   
3  0.611193  1.321678  1.154874  ...  1.860097  1.432840  1.485205  3.058346   
4  0.734499  1.403274  0.211756  ...  2.466252  1.074693  1.005443  2.701354   

         88        89        90        91        92         93  
0  0.991233  2.301178  0.378418  0.301583  1.934144  12.327245  
1  1.167872  4.493270  1.214606  1.169410  2.663392   3.992147  
2  1.166293  5.118066  0.266797  0.231607  1.970670  15.733984  
3  1.113608  3.190772  0.619748  0.531960  1.971293   8.444490  
4  1.184122  5.338463  0.042205  0.036819  1.348709  58.220748  

[5 rows x 94 columns]

In [ ]:
sel2 = sel.transform(X_val)
Xvarthres_val =  pd.DataFrame(sel2)
Xvarthres_val.head()

0         1         2          3         4         5         6   \
0  0.206101  0.196134  1.861980  18.622661  1.620690  1.893169  3.469209   
1  0.064754  0.061613  1.500932  41.128485  1.482298  1.695078  2.835015   
2  1.170486  1.133108  2.589420   4.624101  1.481350  1.444884  4.768313   
3  0.957016  0.904883  2.548556   5.995896  1.599453  1.619644  3.736652   
4  1.143927  1.090907  2.525033   4.946579  1.235520  1.130411  4.907627   

         7         8         9   ...         84        85        86        87  \
0  0.946260  2.562752  0.620846  ...   6.859409  0.560300  0.481991  2.247595   
1  1.149700  4.412102  0.122849  ...  14.075235  0.316020  0.261246  2.063553   
2  0.844821  1.701957  0.844265  ...   5.343799  1.594283  1.640937  3.094673   
3  0.884242  1.707457  1.137405  ...   3.753204  1.553660  1.622424  3.389742   
4  0.662374  1.298889  0.892672  ...   3.678537  1.309785  1.298995  2.862256   

         88         89        90        91        92        93  
0  1.113131   8.797777  0.849327  0.756833  2.469174  6.285164  
1  1.391714  13.130804  0.624897  0.531487  2.620042  8.199596  
2  0.868426   1.981240  1.617649  1.738474  3.872249  2.068008  
3  0.828532   2.345143  1.299062  1.253296  3.347090  3.687073  
4  1.031600   3.388315  1.083188  1.036873  2.486329  5.098603  

[5 rows x 94 columns]

In [ ]:
svclassifier1 = SVC(kernel='rbf').fit(Xvarthres_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_rbf2 = svclassifier1.predict(Xvarthres_val)

print(confusion_matrix(y_val,y_pred_m1_svm_rbf2))
print(classification_report(y_val,y_pred_m1_svm_rbf2))

[[ 2  0  0  1 25  2]
 [ 2  2  0  1 22  3]
 [ 0  1  0  1 28  0]
 [ 1  1  1  2 25  0]
 [ 0  5  1  2 21  1]
 [ 1  5  0  0 19  5]]
              precision    recall  f1-score   support

           0       0.33      0.07      0.11        30
           1       0.14      0.07      0.09        30
           2       0.00      0.00      0.00        30
           3       0.29      0.07      0.11        30
           4       0.15      0.70      0.25        30
           5       0.45      0.17      0.24        30

    accuracy                           0.18       180
   macro avg       0.23      0.18      0.13       180
weighted avg       0.23      0.18      0.13       180



In [ ]:
svclassifier2 = SVC(kernel='poly').fit(Xvarthres_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_polynomial2 = svclassifier2.predict(Xvarthres_val)

print(confusion_matrix(y_val,y_pred_m1_svm_polynomial2))
print(classification_report(y_val,y_pred_m1_svm_polynomial2))

[[ 0  1  0  1 28  0]
 [ 0  1  1  1 27  0]
 [ 0  0  0  1 29  0]
 [ 0  2  1  1 26  0]
 [ 0  2  1  2 25  0]
 [ 0  0  0  0 28  2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.17      0.03      0.06        30
           2       0.00      0.00      0.00        30
           3       0.17      0.03      0.06        30
           4       0.15      0.83      0.26        30
           5       1.00      0.07      0.12        30

    accuracy                           0.16       180
   macro avg       0.25      0.16      0.08       180
weighted avg       0.25      0.16      0.08       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svclassifier3 = SVC(kernel='sigmoid').fit(Xvarthres_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_sigm2 = svclassifier3.predict(Xvarthres_val)

print(confusion_matrix(y_val,y_pred_m1_svm_sigm2))
print(classification_report(y_val,y_pred_m1_svm_sigm2))

[[ 5  0  3  7  3 12]
 [ 6  0  2  4  3 15]
 [ 7  0  4  4  2 13]
 [ 6  2  5  7  4  6]
 [ 8  1  4  2  3 12]
 [ 0  0  6  7  4 13]]
              precision    recall  f1-score   support

           0       0.16      0.17      0.16        30
           1       0.00      0.00      0.00        30
           2       0.17      0.13      0.15        30
           3       0.23      0.23      0.23        30
           4       0.16      0.10      0.12        30
           5       0.18      0.43      0.26        30

    accuracy                           0.18       180
   macro avg       0.15      0.18      0.15       180
weighted avg       0.15      0.18      0.15       180



In [ ]:
rf = RandomForestClassifier().fit(Xvarthres_trainest, y_trainest)

<ipython-input-62-7adb7b3a6529>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf = RandomForestClassifier().fit(Xvarthres_trainest, y_trainest)


In [ ]:
y_pred_m1_rf2 = rf.predict(Xvarthres_val)
print(confusion_matrix(y_val,y_pred_m1_rf2))
print(classification_report(y_val,y_pred_m1_rf2))

[[ 5  3  6  5  8  3]
 [ 8  9  4  5  3  1]
 [ 7  1 11  5  4  2]
 [ 9  4  6  7  2  2]
 [ 2  2  4  9 10  3]
 [ 4  6  7  7  3  3]]
              precision    recall  f1-score   support

           0       0.14      0.17      0.15        30
           1       0.36      0.30      0.33        30
           2       0.29      0.37      0.32        30
           3       0.18      0.23      0.21        30
           4       0.33      0.33      0.33        30
           5       0.21      0.10      0.14        30

    accuracy                           0.25       180
   macro avg       0.25      0.25      0.25       180
weighted avg       0.25      0.25      0.25       180



In [ ]:
gnb = BernoulliNB().fit(Xvarthres_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_naive_bernoulli2 = gnb.predict(Xvarthres_val)
print(confusion_matrix(y_val,y_pred_m1_naive_bernoulli2))
print(classification_report(y_val,y_pred_m1_naive_bernoulli2))

[[28  0  0  2  0  0]
 [28  1  0  1  0  0]
 [29  0  0  1  0  0]
 [29  0  0  1  0  0]
 [29  0  0  1  0  0]
 [30  0  0  0  0  0]]
              precision    recall  f1-score   support

           0       0.16      0.93      0.28        30
           1       1.00      0.03      0.06        30
           2       0.00      0.00      0.00        30
           3       0.17      0.03      0.06        30
           4       0.00      0.00      0.00        30
           5       0.00      0.00      0.00        30

    accuracy                           0.17       180
   macro avg       0.22      0.17      0.07       180
weighted avg       0.22      0.17      0.07       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
model = lgb.LGBMClassifier().fit(Xvarthres_trainest, y_trainest)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000734 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16976


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


[LightGBM] [Info] Number of data points in the train set: 540, number of used features: 94
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, b

In [ ]:
y_pred_m1_lgb2 = model.predict(Xvarthres_val)
print(confusion_matrix(y_val,y_pred_m1_lgb2))
print(classification_report(y_val,y_pred_m1_lgb2))

[[ 8  1  6  6  6  3]
 [ 5  6  5  5  4  5]
 [ 5  3 10  7  5  0]
 [ 8  6  7  7  1  1]
 [ 6  4  4  8  6  2]
 [ 2  8  6  7  2  5]]
              precision    recall  f1-score   support

           0       0.24      0.27      0.25        30
           1       0.21      0.20      0.21        30
           2       0.26      0.33      0.29        30
           3       0.17      0.23      0.20        30
           4       0.25      0.20      0.22        30
           5       0.31      0.17      0.22        30

    accuracy                           0.23       180
   macro avg       0.24      0.23      0.23       180
weighted avg       0.24      0.23      0.23       180



In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

## Select KBest

In [ ]:
#X_new = SelectKBest(f_classif, k=2).fit_transform(X, y)

sb=SelectKBest(f_classif, k=132)
sb1 = sb.fit_transform(X_trainest, y_trainest)
sb2 = sb.fit_transform(X_val, y_val)
#sb1 = sb.transform(X_trainest)

Xuniv_trainest =  pd.DataFrame(sb1)
Xuniv_val =  pd.DataFrame(sb2)

Xuniv_trainest.head()
#sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
#sel1 = sel.fit(X_trainest)
#sel1 = sel.transform(X_trainest)
#Xvarthres_trainest =  pd.DataFrame(sel1)
#Xvarthres_trainest.head()

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0         1         2         3          4         5         6    \
0  0.438319  1.137520  1.089087  2.717865   4.596034  0.906760  2.009526   
1  0.453541  1.035824  0.962622  3.088979   5.301953  0.908564  2.008363   
2  0.287075  0.397559  0.357879  2.113270  12.104865  0.923612  1.996868   
3  0.602902  1.423848  1.415723  3.146533   3.300545  0.902687  1.993667   
4  0.196409  0.136494  0.122143  1.810684  23.507708  0.921866  1.971149   

        7         8         9    ...       122       123       124       125  \
0  0.517826  1.227148  1.021561  ...  2.301178  0.066450  0.255464  0.378418   
1  0.553621  1.228078  1.092782  ...  4.493270  0.056870  0.559084  1.214606   
2  0.650672  1.282335  0.786908  ...  5.118066  0.059250  0.227857  0.266797   
3  0.611193  1.321678  1.154874  ...  3.190772  0.071884  0.351816  0.619748   
4  0.734499  1.403274  0.211756  ...  5.338463  0.102542  0.237914  0.042205   

        126       127       128       129       130        131  
0  0.301583  1.934144  1.787019  1.179408  0.122471  12.327245  
1  1.169410  2.663392  1.491562  1.138520  0.366620   3.992147  
2  0.231607  1.970670  1.708642  1.142292  0.095519  15.733984  
3  0.531960  1.971293  1.740401  1.172728  0.181499   8.444490  
4  0.036819  1.348709  1.360055  1.835939  0.022456  58.220748  

[5 rows x 132 columns]

In [ ]:
Xuniv_val.head()

0         1          2         3         4         5         6    \
0  0.269808  0.088556  18.622661  0.966040  0.381311  1.620690  1.835408   
1  0.218478  0.038263  41.128485  0.946278  0.557951  1.482298  1.817613   
2  0.399456  0.348323   4.624101  0.938113  0.201537  1.481350  1.931166   
3  0.320123  0.269780   5.995896  0.951390  0.363910  1.599453  1.901804   
4  0.462472  0.328719   4.946579  0.905599  0.105569  1.235520  1.985131   

        7         8         9    ...       122       123        124       125  \
0  0.946260  0.644957  2.562752  ...  1.932163  0.192273   8.797777  0.997122   
1  1.149700  0.369327  4.412102  ...  1.868940  0.130888  13.130804  0.999067   
2  0.844821  1.004805  1.701957  ...  1.854642  0.810076   1.981240  0.995693   
3  0.884242  0.973443  1.707457  ...  1.949450  0.707159   2.345143  0.995864   
4  0.662374  1.349299  1.298889  ...  1.754952  0.452675   3.388315  0.987506   

        126       127       128       129       130       131  
0  0.105581  0.306146  0.849327  0.756833  2.469174  0.267132  
1  0.095922  0.301407  0.624897  0.531487  2.620042  0.206928  
2  0.199932  0.734944  1.617649  1.738474  3.872249  0.773545  
3  0.487614  0.382417  1.299062  1.253296  3.347090  0.452147  
4  0.097255  0.399070  1.083188  1.036873  2.486329  0.308553  

[5 rows x 132 columns]

In [ ]:
svclassifier1 = SVC(kernel='rbf').fit(Xuniv_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_rbf2 = svclassifier1.predict(Xuniv_val)

print(confusion_matrix(y_val,y_pred_m1_svm_rbf2))
print(classification_report(y_val,y_pred_m1_svm_rbf2))

[[ 0  0  1  2 27  0]
 [ 0  0  9  2 19  0]
 [ 0  0  0  1 29  0]
 [ 0  0  2  3 25  0]
 [ 0  0  5  4 21  0]
 [ 0  0 10  0 20  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.00      0.00      0.00        30
           2       0.00      0.00      0.00        30
           3       0.25      0.10      0.14        30
           4       0.15      0.70      0.25        30
           5       0.00      0.00      0.00        30

    accuracy                           0.13       180
   macro avg       0.07      0.13      0.06       180
weighted avg       0.07      0.13      0.06       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svclassifier2 = SVC(kernel='poly').fit(Xuniv_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_polynomial2 = svclassifier2.predict(Xuniv_val)

print(confusion_matrix(y_val,y_pred_m1_svm_polynomial2))
print(classification_report(y_val,y_pred_m1_svm_polynomial2))

[[ 0  0  0  0 30  0]
 [ 0  0  0  0 30  0]
 [ 0  0  0  0 30  0]
 [ 0  0  0  0 30  0]
 [ 0  0  0  0 30  0]
 [ 0  0  0  0 30  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.00      0.00      0.00        30
           2       0.00      0.00      0.00        30
           3       0.00      0.00      0.00        30
           4       0.17      1.00      0.29        30
           5       0.00      0.00      0.00        30

    accuracy                           0.17       180
   macro avg       0.03      0.17      0.05       180
weighted avg       0.03      0.17      0.05       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svclassifier3 = SVC(kernel='sigmoid').fit(Xuniv_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_sigm2 = svclassifier3.predict(Xuniv_val)

print(confusion_matrix(y_val,y_pred_m1_svm_sigm2))
print(classification_report(y_val,y_pred_m1_svm_sigm2))

[[ 0  0  0  0 30  0]
 [ 1  0  0  0 29  0]
 [ 0  0  0  0 30  0]
 [ 0  0  0  0 30  0]
 [ 1  0  0  0 29  0]
 [ 3  0  0  0 27  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.00      0.00      0.00        30
           2       0.00      0.00      0.00        30
           3       0.00      0.00      0.00        30
           4       0.17      0.97      0.28        30
           5       0.00      0.00      0.00        30

    accuracy                           0.16       180
   macro avg       0.03      0.16      0.05       180
weighted avg       0.03      0.16      0.05       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
rf = RandomForestClassifier().fit(Xuniv_trainest, y_trainest)

<ipython-input-26-43e1d8b969de>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf = RandomForestClassifier().fit(Xuniv_trainest, y_trainest)


In [ ]:
y_pred_m1_rf2 = rf.predict(Xuniv_val)
print(confusion_matrix(y_val,y_pred_m1_rf2))
print(classification_report(y_val,y_pred_m1_rf2))

[[ 0 12 17  1  0  0]
 [ 0  9 20  1  0  0]
 [ 0  8 20  2  0  0]
 [ 0  9 19  2  0  0]
 [ 0 11 18  1  0  0]
 [ 0 12 18  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.15      0.30      0.20        30
           2       0.18      0.67      0.28        30
           3       0.29      0.07      0.11        30
           4       0.00      0.00      0.00        30
           5       0.00      0.00      0.00        30

    accuracy                           0.17       180
   macro avg       0.10      0.17      0.10       180
weighted avg       0.10      0.17      0.10       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
gnb = BernoulliNB().fit(Xuniv_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_naive_bernoulli2 = gnb.predict(Xuniv_val)
print(confusion_matrix(y_val,y_pred_m1_naive_bernoulli2))
print(classification_report(y_val,y_pred_m1_naive_bernoulli2))

[[28  2  0  0  0  0]
 [29  0  1  0  0  0]
 [30  0  0  0  0  0]
 [29  0  1  0  0  0]
 [29  0  0  1  0  0]
 [30  0  0  0  0  0]]
              precision    recall  f1-score   support

           0       0.16      0.93      0.27        30
           1       0.00      0.00      0.00        30
           2       0.00      0.00      0.00        30
           3       0.00      0.00      0.00        30
           4       0.00      0.00      0.00        30
           5       0.00      0.00      0.00        30

    accuracy                           0.16       180
   macro avg       0.03      0.16      0.05       180
weighted avg       0.03      0.16      0.05       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
model = lgb.LGBMClassifier().fit(Xuniv_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001168 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 23673
[LightGBM] [Info] Number of data points in the train set: 540, number of used features: 132
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [

In [ ]:
y_pred_m1_lgb2 = model.predict(Xuniv_val)
print(confusion_matrix(y_val,y_pred_m1_lgb2))
print(classification_report(y_val,y_pred_m1_lgb2))

[[ 0  9 13  3  0  5]
 [ 0  7 14  6  1  2]
 [ 0 11 11  1  0  7]
 [ 0  4 16  4  1  5]
 [ 0  3 16  6  0  5]
 [ 0  4 14  6  2  4]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.18      0.23      0.21        30
           2       0.13      0.37      0.19        30
           3       0.15      0.13      0.14        30
           4       0.00      0.00      0.00        30
           5       0.14      0.13      0.14        30

    accuracy                           0.14       180
   macro avg       0.10      0.14      0.11       180
weighted avg       0.10      0.14      0.11       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#from sklearn.feature_selection import RFECV
#from sklearn.linear_model import LogisticRegression
#from sklearn.model_selection import StratifiedKFold

#min_features_to_select = 1  # Minimum number of features to consider
#clf = LogisticRegression()
#cv = StratifiedKFold(11)

#rfecv = RFECV(
    #estimator=clf,
    #step=24,
    #cv=cv,
    #scoring="accuracy",
    #min_features_to_select=min_features_to_select,
    #n_jobs=6,
#)
#rfecv.fit(X_train, y_train)

#print(f"Optimal number of features: {rfecv.n_features_}")

In [ ]:
#import matplotlib.pyplot as plt

#n_scores = len(rfecv.cv_results_["mean_test_score"])
#plt.figure()
#plt.xlabel("Number of features selected")
#plt.ylabel("Mean test accuracy")
#plt.errorbar(
    #range(min_features_to_select, n_scores + min_features_to_select),
    #rfecv.cv_results_["mean_test_score"],
    #yerr=rfecv.cv_results_["std_test_score"],
#)
#set_xlim(1, 24)
#plt.title("Recursive Feature Elimination \nwith correlated features")
#plt.show()

## Linear SVC

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

In [ ]:
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_trainest, y_trainest)
model = SelectFromModel(lsvc, prefit=True)
l1trainest = model.transform(X_trainest)
l1val = model.transform(X_val)

Xl1_trainest =  pd.DataFrame(l1trainest)
Xl1_val =  pd.DataFrame(l1val)

Xl1_trainest

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(


0          1          2          3          4         5   \
0     4.596034   1.227148   5.110086   5.424171   9.909207  3.067457   
1     5.301953   1.228078   4.935541   8.536667   4.333105  2.157598   
2    12.104865   1.282335   7.033372  13.074808   7.067764  2.344368   
3     3.300545   1.321678   3.859082   6.489563   5.374721  1.831514   
4    23.507708   1.403274  18.254820  14.278848  29.259056  2.059803   
..         ...        ...        ...        ...        ...       ...   
535   4.776861  15.419387   6.792499   4.338346   7.167898  2.559836   
536   9.451764  89.750708  12.282032  17.510564  17.335870  2.490278   
537   8.261131  14.460381   4.491215   4.128617  15.802901  2.344819   
538  12.297947  19.677247   4.919417   7.488593   9.654935  2.433486   
539   4.647519  11.497887   6.239821   6.135943   5.473517  3.087599   

            6          7         8         9   ...        20         21  \
0     3.308217   4.030111  4.535524  1.224870  ...  5.999860   6.299656   
1     9.683650  15.566996  0.000000  0.000000  ...  6.160684   3.988495   
2     7.791326   5.073758  0.000000  0.000000  ...  4.645581   2.726477   
3    16.162275   3.995645  6.112549  1.187225  ...  5.798937   4.419663   
4    11.587203   6.572597  0.000000  0.000000  ...  4.868731  14.306013   
..         ...        ...       ...       ...  ...       ...        ...   
535   8.555525   6.232039  4.084430  1.575977  ...  6.198578   2.599347   
536   4.001354   5.415922  3.536136  1.832272  ...  6.126741   4.389708   
537   6.058397   5.657450  2.257286  5.131698  ...  6.007266   3.881031   
538   6.672602   8.054909  3.085745  2.009574  ...  4.966268  12.971168   
539   3.208753   4.102373  3.813675  1.734255  ...  4.897888   7.860512   

           22         23        24        25         26        27        28  \
0    1.877423  15.725851  4.621865  4.286656   1.735719  2.301178  1.934144   
1    3.002595   2.505449  4.619497  2.595852   4.164196  4.493270  2.663392   
2    2.584865   4.932094  4.714651  3.604551   3.465410  5.118066  1.970670   
3    2.326800   9.917249  5.766546  4.284942   1.860097  3.190772  1.971293   
4    2.105986  10.465841  5.719992  3.595800   2.466252  5.338463  1.348709   
..        ...        ...       ...       ...        ...       ...       ...   
535  2.161681  13.349459  5.988765  2.287049  10.780003  4.347989  2.313929   
536  2.482352   5.427041  4.740968  2.802263   3.771807  7.591976  2.691081   
537  2.177645   7.677692  5.915204  2.574876   4.870088  8.635975  2.696721   
538  2.034993  12.757363  6.153128  2.532973   6.974263  7.441321  2.274052   
539  2.667249   4.341399  4.760150  3.435661   2.814681  7.724647  2.576468   

            29  
0    12.327245  
1     3.992147  
2    15.733984  
3     8.444490  
4    58.220748  
..         ...  
535   8.397645  
536   5.731876  
537   4.944807  
538   9.545513  
539   4.702300  

[540 rows x 30 columns]

In [ ]:
Xl1_val

0         1          2          3           4         5   \
0    18.622661  2.562752   8.953466   9.901267   11.937026  2.698239   
1    41.128485  4.412102  25.740543  25.702602   37.899873  1.744755   
2     4.624101  1.701957   6.517208   8.979211    5.390198  3.227782   
3     5.995896  1.707457   4.502885   6.557770    6.591880  3.576683   
4     4.946579  1.298889   6.119741   7.479921    7.084363  2.491487   
..         ...       ...        ...        ...         ...       ...   
175  10.171564  7.564983  45.991559   8.096884   35.152745  4.013533   
176   8.809151  8.366517  70.908862  21.594289  100.768074  1.707906   
177  11.952542  3.508289   9.139886   7.134817    5.605175  2.659916   
178  12.813560  9.543088  12.080123  10.694777    9.762641  2.028293   
179  93.941049  8.622963  54.762608  11.648335   41.310617  1.606788   

            6          7         8          9   ...        20         21  \
0     6.126740  28.857442  2.010220  16.932597  ...  4.686016   8.554460   
1    27.153600  26.645982  1.708113  14.750371  ...  5.791727  53.549235   
2     3.812552   4.336125  2.176004   9.313744  ...  5.687923   8.471490   
3     2.480942   5.529021  2.316522   7.389965  ...  5.944544   4.345138   
4     4.719923   3.767815  2.107344   9.827542  ...  6.029526   5.181930   
..         ...        ...       ...        ...  ...       ...        ...   
175   2.213375  18.561437  3.850334   2.309351  ...  4.902756  28.694514   
176  24.029180  16.946469  3.214366   2.594191  ...  6.096696  78.730806   
177   5.171072   4.268606  3.353336   2.470609  ...  6.018388  31.014506   
178  10.678582  10.018230  3.685689   2.110561  ...  6.221405  51.801574   
179  27.956168  47.060599  3.327657   3.054943  ...  5.988765  32.685300   

           22          23        24        25         26         27        28  \
0    2.593146    6.622067  5.784524  2.772748   6.859409   8.797777  2.469174   
1    1.929388   15.113911  4.738573  1.965259  14.075235  13.130804  2.620042   
2    2.892817    4.615790  5.687923  2.754702   5.343799   1.981240  3.872249   
3    3.016379    4.161578  5.522500  3.312560   3.753204   2.345143  3.347090   
4    3.285422    2.952252  4.686016  3.287516   3.678537   3.388315  2.486329   
..        ...         ...       ...       ...        ...        ...       ...   
175  1.500627   43.728385  5.806153  3.002271   2.421954  14.691306  2.468842   
176  1.483306   48.089378  5.937199  1.973950  15.902250   8.582884  1.994074   
177  2.371467    6.928265  6.085460  3.135618   3.262321  13.058976  1.450704   
178  1.450910   50.644660  6.259605  1.935201  16.635507  44.859558  2.695894   
179  1.258563  134.207076  5.791727  2.427507  10.827962  58.856003  1.675345   

            29  
0     6.285164  
1     8.199596  
2     2.068008  
3     3.687073  
4     5.098603  
..         ...  
175   5.990757  
176  13.601493  
177  63.964539  
178   5.068429  
179  36.323279  

[180 rows x 30 columns]

In [ ]:
svclassifier1 = SVC(kernel='rbf').fit(Xl1_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_rbf2 = svclassifier1.predict(Xl1_val)

print(confusion_matrix(y_val,y_pred_m1_svm_rbf2))
print(classification_report(y_val,y_pred_m1_svm_rbf2))

[[ 2  0  0  1 24  3]
 [ 2  2  0  1 22  3]
 [ 1  1  0  1 27  0]
 [ 1  1  1  2 25  0]
 [ 0  5  1  2 21  1]
 [ 1  5  0  0 19  5]]
              precision    recall  f1-score   support

           0       0.29      0.07      0.11        30
           1       0.14      0.07      0.09        30
           2       0.00      0.00      0.00        30
           3       0.29      0.07      0.11        30
           4       0.15      0.70      0.25        30
           5       0.42      0.17      0.24        30

    accuracy                           0.18       180
   macro avg       0.21      0.18      0.13       180
weighted avg       0.21      0.18      0.13       180



In [ ]:
svclassifier2 = SVC(kernel='poly').fit(Xl1_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_polynomial2 = svclassifier2.predict(Xl1_val)

print(confusion_matrix(y_val,y_pred_m1_svm_polynomial2))
print(classification_report(y_val,y_pred_m1_svm_polynomial2))

[[ 0  1  0  1 28  0]
 [ 0  1  1  1 27  0]
 [ 0  0  0  1 29  0]
 [ 0  1  1  1 26  1]
 [ 0  2  0  3 25  0]
 [ 0  1  0  0 27  2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.17      0.03      0.06        30
           2       0.00      0.00      0.00        30
           3       0.14      0.03      0.05        30
           4       0.15      0.83      0.26        30
           5       0.67      0.07      0.12        30

    accuracy                           0.16       180
   macro avg       0.19      0.16      0.08       180
weighted avg       0.19      0.16      0.08       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svclassifier3 = SVC(kernel='sigmoid').fit(Xl1_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_sigm2 = svclassifier3.predict(Xl1_val)

print(confusion_matrix(y_val,y_pred_m1_svm_sigm2))
print(classification_report(y_val,y_pred_m1_svm_sigm2))

[[ 3  0  3  6  6 12]
 [ 4  0  2  3  5 16]
 [ 1  0  7  2  6 14]
 [ 4  2  6  3  7  8]
 [ 4  0  3  3  8 12]
 [ 0  0  6  6  4 14]]
              precision    recall  f1-score   support

           0       0.19      0.10      0.13        30
           1       0.00      0.00      0.00        30
           2       0.26      0.23      0.25        30
           3       0.13      0.10      0.11        30
           4       0.22      0.27      0.24        30
           5       0.18      0.47      0.26        30

    accuracy                           0.19       180
   macro avg       0.16      0.19      0.17       180
weighted avg       0.16      0.19      0.17       180



In [ ]:
rf = RandomForestClassifier().fit(Xl1_trainest, y_trainest)

<ipython-input-33-ef4e91ab2b1c>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf = RandomForestClassifier().fit(Xl1_trainest, y_trainest)


In [ ]:
y_pred_m1_rf2 = rf.predict(Xl1_val)
print(confusion_matrix(y_val,y_pred_m1_rf2))
print(classification_report(y_val,y_pred_m1_rf2))

[[ 6  4  7  5  6  2]
 [ 6  6  5  9  3  1]
 [ 5  3  9  6  5  2]
 [ 2  7 12  6  2  1]
 [ 8  1  4  6  5  6]
 [ 2 10  7  6  2  3]]
              precision    recall  f1-score   support

           0       0.21      0.20      0.20        30
           1       0.19      0.20      0.20        30
           2       0.20      0.30      0.24        30
           3       0.16      0.20      0.18        30
           4       0.22      0.17      0.19        30
           5       0.20      0.10      0.13        30

    accuracy                           0.19       180
   macro avg       0.20      0.19      0.19       180
weighted avg       0.20      0.19      0.19       180



In [ ]:
gnb = BernoulliNB().fit(Xl1_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_naive_bernoulli2 = gnb.predict(Xl1_val)
print(confusion_matrix(y_val,y_pred_m1_naive_bernoulli2))
print(classification_report(y_val,y_pred_m1_naive_bernoulli2))

[[28  0  0  2  0  0]
 [29  0  0  1  0  0]
 [29  0  0  1  0  0]
 [29  0  0  1  0  0]
 [29  0  0  1  0  0]
 [30  0  0  0  0  0]]
              precision    recall  f1-score   support

           0       0.16      0.93      0.27        30
           1       0.00      0.00      0.00        30
           2       0.00      0.00      0.00        30
           3       0.17      0.03      0.06        30
           4       0.00      0.00      0.00        30
           5       0.00      0.00      0.00        30

    accuracy                           0.16       180
   macro avg       0.05      0.16      0.06       180
weighted avg       0.05      0.16      0.06       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
model = lgb.LGBMClassifier().fit(Xl1_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000304 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5417
[LightGBM] [Info] Number of data points in the train set: 540, number of used features: 30
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Wa

In [ ]:
y_pred_m1_lgb2 = model.predict(Xl1_val)
print(confusion_matrix(y_val,y_pred_m1_lgb2))
print(classification_report(y_val,y_pred_m1_lgb2))

[[ 5  5  6  3  9  2]
 [ 4  9  5  1  8  3]
 [ 8  5  6  5  6  0]
 [ 3 10  8  4  4  1]
 [ 3  8  4  6  7  2]
 [ 1  8  7  6  4  4]]
              precision    recall  f1-score   support

           0       0.21      0.17      0.19        30
           1       0.20      0.30      0.24        30
           2       0.17      0.20      0.18        30
           3       0.16      0.13      0.15        30
           4       0.18      0.23      0.21        30
           5       0.33      0.13      0.19        30

    accuracy                           0.19       180
   macro avg       0.21      0.19      0.19       180
weighted avg       0.21      0.19      0.19       180



## Extra Tree Classifier

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
clf = ExtraTreesClassifier(n_estimators=50)
clf = clf.fit(X_trainest, y_trainest)
clf.feature_importances_
model = SelectFromModel(clf, prefit=True)
clf1 = model.transform(X_trainest)
clf3 = model.transform(X_val)
Xtree_trainest =  pd.DataFrame(clf1)
Xtree_val =  pd.DataFrame(clf3)

Xtree_trainest

<ipython-input-18-4ea70219c942>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf = clf.fit(X_trainest, y_trainest)
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(


0         1         2         3         4         5         6    \
0    0.067259  1.137520  1.089087  0.918782  1.180104  1.072182  1.031187   
1    0.298309  1.035824  0.962622  0.935729  1.195381  1.096464  1.030471   
2    0.058871  0.397559  0.357879  0.932941  1.250260  1.146009  1.030720   
3    0.057681  1.423848  1.415723  0.889365  1.232010  1.139352  1.030627   
4    0.025413  0.136494  0.122143  0.901987  1.295083  1.204223  1.030284   
..        ...       ...       ...       ...       ...       ...       ...   
535  0.076647  1.113328  1.058204  0.274030  0.276570  0.253868  1.027773   
536  0.021446  0.552228  0.495272  0.128761  0.023061  0.020645  1.026474   
537  0.024979  0.707784  0.646462  0.228445  0.315428  0.285424  1.027615   
538  0.075441  0.403504  0.361225  0.298267  0.194238  0.181537  1.026378   
539  0.068627  1.107048  1.035529  0.314238  0.442713  0.386771  1.026505   

          7         8         9    ...       115       116       117  \
0    1.459836  0.015239  0.472282  ...  0.988612  0.729572  1.786127   
1    1.445315  0.027380  0.331913  ...  0.977801  0.520886  1.465573   
2    1.370945  0.023555  0.273679  ...  0.988423  0.421195  1.680360   
3    1.350561  0.017967  0.519722  ...  0.994916  0.578065  1.746511   
4    1.238499  0.038805  0.380087  ...  0.982817  0.374628  1.521427   
..        ...       ...       ...  ...       ...       ...       ...   
535  0.098909  0.120325  0.310917  ...  0.980655  0.501569  1.714981   
536  0.015331  0.108747  0.216825  ...  0.996508  0.192600  1.832783   
537  0.104851  0.068059  0.429676  ...  0.988057  0.307172  1.761941   
538  0.072445  0.064198  0.498361  ...  0.979165  0.319010  1.678225   
539  0.127246  0.068174  0.479237  ...  0.981232  0.229568  1.790950   

          118       119       120       121       122       123       124  
0    0.975591  0.378418  0.301583  1.934144  1.787019  1.179408  0.122471  
1    0.978876  1.214606  1.169410  2.663392  1.491562  1.138520  0.366620  
2    0.984789  0.266797  0.231607  1.970670  1.708642  1.142292  0.095519  
3    0.983473  0.619748  0.531960  1.971293  1.740401  1.172728  0.181499  
4    0.967654  0.042205  0.036819  1.348709  1.360055  1.835939  0.022456  
..        ...       ...       ...       ...       ...       ...       ...  
535  0.980907  0.634272  0.558961  2.313929  1.648317  1.483902  0.183832  
536  0.990362  0.904297  0.809234  2.691081  1.774181  1.126665  0.284591  
537  0.979751  1.102213  1.041617  2.696721  1.696681  1.111990  0.313017  
538  0.976851  0.570826  0.506152  2.274052  1.682471  1.326216  0.156895  
539  0.995086  1.148300  1.088418  2.576468  1.798309  1.140475  0.351366  

[540 rows x 125 columns]

In [ ]:
Xtree_val

0         1         2         3         4         5         6    \
0    0.051621  0.206101  0.196134  0.580470  1.620690  1.893169  1.029252   
1    0.102932  0.064754  0.061613  0.388544  1.482298  1.695078  1.029377   
2    0.017636  1.170486  1.133108  0.789492  1.481350  1.444884  1.030159   
3    0.018601  0.957016  0.904883  0.826550  1.599453  1.619644  1.030003   
4    0.016566  1.143927  1.090907  0.923145  1.235520  1.130411  1.030440   
..        ...       ...       ...       ...       ...       ...       ...   
175  0.023091  0.010222  0.009194  0.223085  0.018531  0.016509  1.025134   
176  0.013519  0.180373  0.162540  0.247410  0.282843  0.258268  1.025358   
177  0.011702  0.047656  0.039647  0.182306  0.079400  0.064869  1.026886   
178  0.062681  0.025660  0.024187  0.129939  0.102522  0.094034  1.026696   
179  0.025261  0.134647  0.119047  0.362694  0.326884  0.212022  1.028025   

          7         8         9    ...       115       116       117  \
0    0.644957  0.044199  0.349059  ...  0.991811  0.288661  1.932163   
1    0.369327  0.073101  0.169432  ...  0.997583  0.216171  1.868940   
2    1.004805  0.046230  0.425479  ...  0.988275  0.726872  1.854642   
3    0.973443  0.040031  0.524481  ...  0.990687  0.482790  1.949450   
4    1.349299  0.042674  0.437635  ...  0.979872  0.464698  1.754952   
..        ...       ...       ...  ...       ...       ...       ...   
175  0.011367  0.013309  0.121569  ...  0.942483  0.119835  1.435831   
176  0.097148  0.025673  0.270307  ...  0.979073  0.294020  1.793859   
177  0.046963  0.028324  0.265607  ...  0.967182  0.050431  1.724353   
178  0.050743  0.034487  0.111917  ...  0.968233  0.209038  1.639971   
179  0.166236  0.042062  0.232606  ...  0.979732  0.208085  1.701935   

          118       119       120       121       122       123       124  
0    0.997122  0.849327  0.756833  2.469174  1.913739  1.151683  0.267132  
1    0.999067  0.624897  0.531487  2.620042  1.862623  1.391247  0.206928  
2    0.995693  1.617649  1.738474  3.872249  1.863218  0.952004  0.773545  
3    0.995864  1.299062  1.253296  3.347090  1.920830  0.963859  0.452147  
4    0.987506  1.083188  1.036873  2.486329  1.858499  1.083576  0.308553  
..        ...       ...       ...       ...       ...       ...       ...  
175  0.974850  0.074452  0.072896  1.617265  1.805961  1.373865  0.038867  
176  0.975878  0.786438  0.678459  2.299244  1.900372  0.966266  0.242985  
177  0.985842  0.365137  0.318589  1.990945  1.884109  1.172551  0.118945  
178  0.975862  0.305499  0.266874  1.759670  1.745421  1.634131  0.118662  
179  0.977532  0.071539  0.060205  1.500570  1.688890  1.486604  0.045165  

[180 rows x 125 columns]

In [ ]:
svclassifier1 = SVC(kernel='rbf').fit(Xtree_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_rbf2 = svclassifier1.predict(Xtree_val)

print(confusion_matrix(y_val,y_pred_m1_svm_rbf2))
print(classification_report(y_val,y_pred_m1_svm_rbf2))

[[ 1  1 24  0  4  0]
 [ 0  2 19  1  7  1]
 [ 1  2 26  0  0  1]
 [ 1  1 25  2  1  0]
 [ 2  2 21  0  3  2]
 [ 2  5 18  1  4  0]]
              precision    recall  f1-score   support

           0       0.14      0.03      0.05        30
           1       0.15      0.07      0.09        30
           2       0.20      0.87      0.32        30
           3       0.50      0.07      0.12        30
           4       0.16      0.10      0.12        30
           5       0.00      0.00      0.00        30

    accuracy                           0.19       180
   macro avg       0.19      0.19      0.12       180
weighted avg       0.19      0.19      0.12       180



In [ ]:
svclassifier2 = SVC(kernel='poly').fit(Xtree_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_polynomial2 = svclassifier2.predict(Xtree_val)

print(confusion_matrix(y_val,y_pred_m1_svm_polynomial2))
print(classification_report(y_val,y_pred_m1_svm_polynomial2))

[[ 0  0  1  0 29  0]
 [ 0  1  1  0 27  1]
 [ 0  0  0  0 29  1]
 [ 0  0  0  1 29  0]
 [ 0  0  1  0 28  1]
 [ 0  1  1  0 28  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.50      0.03      0.06        30
           2       0.00      0.00      0.00        30
           3       1.00      0.03      0.06        30
           4       0.16      0.93      0.28        30
           5       0.00      0.00      0.00        30

    accuracy                           0.17       180
   macro avg       0.28      0.17      0.07       180
weighted avg       0.28      0.17      0.07       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svclassifier3 = SVC(kernel='sigmoid').fit(Xtree_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_svm_sigm2 = svclassifier3.predict(Xtree_val)

print(confusion_matrix(y_val,y_pred_m1_svm_sigm2))
print(classification_report(y_val,y_pred_m1_svm_sigm2))

[[ 0  0  8  2  9 11]
 [ 0  0  2  2 11 15]
 [ 0  2  4  2 10 12]
 [ 1  0  5  2 14  8]
 [ 0  1  3  0 13 13]
 [ 0  0  5  1  9 15]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.00      0.00      0.00        30
           2       0.15      0.13      0.14        30
           3       0.22      0.07      0.10        30
           4       0.20      0.43      0.27        30
           5       0.20      0.50      0.29        30

    accuracy                           0.19       180
   macro avg       0.13      0.19      0.13       180
weighted avg       0.13      0.19      0.13       180



In [ ]:
rf = RandomForestClassifier().fit(Xtree_trainest, y_trainest)

<ipython-input-24-489f5c12fa2a>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf = RandomForestClassifier().fit(Xtree_trainest, y_trainest)


In [ ]:
y_pred_m1_rf2 = rf.predict(Xtree_val)
print(confusion_matrix(y_val,y_pred_m1_rf2))
print(classification_report(y_val,y_pred_m1_rf2))

[[ 9  0 10  4  4  3]
 [ 5  6  4  5  6  4]
 [ 8  1 16  2  2  1]
 [ 8  2 11  2  4  3]
 [ 6  5  4  7  5  3]
 [ 5  3  9  2  3  8]]
              precision    recall  f1-score   support

           0       0.22      0.30      0.25        30
           1       0.35      0.20      0.26        30
           2       0.30      0.53      0.38        30
           3       0.09      0.07      0.08        30
           4       0.21      0.17      0.19        30
           5       0.36      0.27      0.31        30

    accuracy                           0.26       180
   macro avg       0.26      0.26      0.24       180
weighted avg       0.26      0.26      0.24       180



In [ ]:
gnb = BernoulliNB().fit(Xtree_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred_m1_naive_bernoulli2 = gnb.predict(Xtree_val)
print(confusion_matrix(y_val,y_pred_m1_naive_bernoulli2))
print(classification_report(y_val,y_pred_m1_naive_bernoulli2))

[[27  0  0  3  0  0]
 [28  1  0  1  0  0]
 [29  0  0  1  0  0]
 [28  0  0  2  0  0]
 [29  0  0  1  0  0]
 [29  0  0  1  0  0]]
              precision    recall  f1-score   support

           0       0.16      0.90      0.27        30
           1       1.00      0.03      0.06        30
           2       0.00      0.00      0.00        30
           3       0.22      0.07      0.10        30
           4       0.00      0.00      0.00        30
           5       0.00      0.00      0.00        30

    accuracy                           0.17       180
   macro avg       0.23      0.17      0.07       180
weighted avg       0.23      0.17      0.07       180



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
model = lgb.LGBMClassifier().fit(Xtree_trainest, y_trainest)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001211 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 22302
[LightGBM] [Info] Number of data points in the train set: 540, number of used features: 125
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [

In [ ]:
y_pred_m1_lgb2 = model.predict(Xtree_val)
print(confusion_matrix(y_val,y_pred_m1_lgb2))
print(classification_report(y_val,y_pred_m1_lgb2))

[[ 7  5  5  6  4  3]
 [ 4  6  7  8  2  3]
 [ 7  2 12  6  3  0]
 [ 5  5 12  4  4  0]
 [ 5  4  8  7  3  3]
 [ 3  4  9  4  6  4]]
              precision    recall  f1-score   support

           0       0.23      0.23      0.23        30
           1       0.23      0.20      0.21        30
           2       0.23      0.40      0.29        30
           3       0.11      0.13      0.12        30
           4       0.14      0.10      0.12        30
           5       0.31      0.13      0.19        30

    accuracy                           0.20       180
   macro avg       0.21      0.20      0.19       180
weighted avg       0.21      0.20      0.19       180



In [ ]:
fva = '/content/drive/MyDrive/iCV/fs/f_val0912_raw.csv'
f_val = pd.read_csv(fva)
f_val = f_val.iloc[: , 1:]
f_val

filename
0    user02_raw_02.csv
1    user02_raw_01.csv
2    user02_raw_08.csv
3    user02_raw_06.csv
4    user02_raw_11.csv
..                 ...
175  user35_raw_05.csv
176  user35_raw_06.csv
177  user35_raw_07.csv
178  user35_raw_08.csv
179  user35_raw_09.csv

[180 rows x 1 columns]

In [ ]:
X_va_values= pd.DataFrame()
X_va_values['file'] = f_val['filename']
X_va_values['GT'] = y_val['label']
X_va_values['preds'] = y_pred_m1_rf2.tolist()
encode_lbl = {1:"fear", 2:"joy", 3:"disgust", 4:"sadness", 5:"surprise", 0:"anger"}
X_va_values = X_va_values.replace(encode_lbl)

X_va_values

file        GT    preds
0    user02_raw_02.csv      fear    anger
1    user02_raw_01.csv   sadness  disgust
2    user02_raw_08.csv   disgust  sadness
3    user02_raw_06.csv     anger      joy
4    user02_raw_11.csv     anger  disgust
..                 ...       ...      ...
175  user35_raw_05.csv      fear  disgust
176  user35_raw_06.csv  surprise    anger
177  user35_raw_07.csv   disgust    anger
178  user35_raw_08.csv      fear  disgust
179  user35_raw_09.csv  surprise  disgust

[180 rows x 3 columns]

In [ ]:
X_va_values.to_csv('/content/drive/MyDrive/iCV/fs/X_train+test_val1912_raw.csv')